---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes #same sudo apt update

  - name: install apache2 package
    apt:
      name: apache2
      status: latest

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      status: latest
